name: "PR Triage"

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign author
        uses: toshimaru/auto-author-assign@v2.1.1
